name: recipe_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.1
  get: ^4.6.6
  google_fonts: ^6.2.1
  country_list_pick: ^1.0.1+6
  otp_text_field: ^1.1.3
  flutter_otp_text_field: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
     - assets/common/
     - assets/icons/
  #   - images/a_dot_ham.jpeg
