name: recipe_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.1
  get: ^4.6.6
  google_fonts: ^6.2.1
  country_list_pick: ^1.0.1+6
  otp_text_field: ^1.1.3
  flutter_otp_text_field: ^1.2.0
  http: ^1.2.2
  webview_flutter: ^4.9.0
  shared_preferences: ^2.3.2
  fluttertoast: ^8.2.8

  # --- firebase ---
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
     - assets/common/
     - assets/icons/
  #   - images/a_dot_ham.jpeg
