// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0NowWFZlJGYC6IIwtBsoaozp7-2uxDTM',
    appId: '1:1091894881418:android:e358f796e94dc650f69173',
    messagingSenderId: '1091894881418',
    projectId: 'recipe-app-3f25f',
    storageBucket: 'recipe-app-3f25f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBukrj5U84pLlBJDoTa1zRy41BnfztVG4k',
    appId: '1:1091894881418:ios:24b5697c9a6c1c8ef69173',
    messagingSenderId: '1091894881418',
    projectId: 'recipe-app-3f25f',
    storageBucket: 'recipe-app-3f25f.appspot.com',
    iosBundleId: 'com.example.recipeApp',
  );
}

/*
Platform  Firebase App Id
android   1:1091894881418:android:e358f796e94dc650f69173
ios       1:1091894881418:ios:24b5697c9a6c1c8ef69173
 */
